[package]
name = "ryzom-patch-info"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
enum-ordinalize = { version = "4.3.2" }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }